name: 'unity runner'
description: 'Convenient use of the Unity command line in GitHub Actions.'
inputs:
  username:
    description: 'Unity account username'
    required: true
  unity-password:
    description: 'Unity account password'
    required: true
  serial:
    description: 'Unity license serial key. Used for Plus/Pro license activation.'
    required: false
  execute-method:
    description: 'Execute the static method as soon as Unity opens the project.'
    required: true
    default: ''
  disable-gpu-skinning:
    description: 'Disable Graphics Processing Unit (GPU) skinning at startup.'
    required: false
runs:
  using: 'node20'
  main: 'src/run.js'
  post: 'cleanup.js'