name: 'unity runner'
description: 'Convenient use of the Unity command line in GitHub Actions.'
inputs:
  unity-path:
    description: 'Path of Unity.exe'
    required: true
  unity-username:
    description: 'Unity account username'
    required: false
  unity-password:
    description: 'Unity account password'
    required: false
  unity-serial:
    description: 'Unity license serial key. Used for Plus/Pro license activation.'
    required: false
  unity-ulf:
    description: 'Unity ulf file. Used for Personal license activation.'
    required: false
  project-path:
    description: 'Unity project path. '
    required: false
  execute-method:
    description: 'Execute the static method as soon as Unity opens the project.'
    required: false
  create-manual-activation-file:
    description: ' '
    required: false
runs:
  using: 'node20'
  main: 'src/main.js'